# Generated by Django 3.1.6 on 2022-03-13 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='fileUpload',
            fields=[
                ('name', models.AutoField(primary_key=True, serialize=False)),
                ('audioFile', models.FileField(upload_to='')),
            ],
        ),
    ]
