# Generated by Django 3.1.6 on 2022-03-13 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='audioFile',
            field=models.FileField(upload_to='media/'),
        ),
    ]
